#!/bin/bash

echo "Backing up current iptable rules"

sudo iptables-save > ~/firewall.rules

sudo iptables -X
sudo iptables -t nat -F
sudo iptables -t nat -X
sudo iptables -t mangle -F
sudo iptables -t mangle -X
sudo iptables -P INPUT ACCEPT
sudo iptables -P FORWARD ACCEPT
sudo iptables -P OUTPUT ACCEPT

echo "Dsiabling ufw"

sudo ufw disable
